# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci(github-actions): "
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci(python): "
    groups:
      patch-and-minor-updates:
        update-types: ["patch", "minor"]
      major-updates:
        update-types: ["major"]
    open-pull-requests-limit: 4
    cooldown:
      semver-patch-days: 5
      semver-minor-days: 15
      semver-major-days: 30
